### ISSUE TITLE
About the visualization of the ring pattern in Fourier domain

### ISSUE THREAD

**Issue by qilong-zhang** [YuxinWenRick/tree-ring-watermark#16]
Hi Yuxin, 

Your work is really intersting and novel! 
I want to further understand the detail of your method. However, I have trouble visualizing the watermark pattern. I notice 
that `gt_patch` is (1,4,64,64) and I can observe the ring in each channel, while I cannot find that in 
that `init_latents_w`, `reversed_latents_no_w` and `reversed_latents_w`. 
Could you help me? Thanks!

**Comment by YuxinWenRick** [comment]
Hi Qilong, thanks for your interest!

`gt_patch` contains the ring pattern in every channel as a key, but for init_latents_w, we only inject the key into one of the channels. If you are running `python run_tree_ring_watermark.py --run_name no_attack --w_channel 3 --w_pattern ring --start 0 --end 1000 --with_tracking --reference_model ViT-g-14 --reference_model_pretrain laion2b_s12b_b42k`, you would expect the pattern is in the last channel since `--w_channel 3`. Could you double-check if you can see it in the last channel? Also, I don't think we expect any ring pattern for `reversed_latents_no_w` since it's not watermarked.

Let me know if you have further questions!

**Comment by qilong-zhang** [comment]
@YuxinWenRick Thanks for your reply. I visualize the pattern by the following code:
```python
import matplotlib.pyplot as plt

plt.figure(figsize=(20,4))
plt.title(current_prompt)
plt.subplot(151)
plt.imshow(orig_image_no_w)
plt.subplot(152)
plt.imshow(orig_image_w)
plt.subplot(153)
vis_nowm = reversed_latents_no_w[0,3,...].detach().cpu()
plt.imshow((vis_nowm-vis_nowm.min())/(vis_nowm.max()-vis_nowm.min()))
plt.subplot(154)
vis_wm = reversed_latents_w[0,3,...].detach().cpu()
plt.imshow((vis_wm-vis_wm.min())/(vis_wm.max()-vis_wm.min()))
plt.subplot(155)
vis_wm2 = init_latents_w[0,3,...].detach().cpu()
plt.imshow((vis_wm2-vis_wm2.min())/(vis_wm2.max()-vis_wm2.min()))
plt.savefig('vis/{}.png'.format(i), dpi = 800)
plt.close()
```

And the result is 
![16](https://github.com/YuxinWenRick/tree-ring-watermark/assets/30571468/364bc773-366f-4883-872d-4f4acbd5602c)

Is this correct? There seems to be a weak "ring" on the edge.

**Comment by zzzucf** [comment]
Hi, I wonder how to visualize the gt_patch, just like what paper shows in Figure 1? It is complex type.

**Comment by YuxinWenRick** [comment]
Hi @zzzucf , yeah, you are right that we cannot really visualize the complex numbers, so the figure shown in the paper is just the visualization of the real part. You can follow this [code](https://github.com/YuxinWenRick/tree-ring-watermark/issues/19#issuecomment-1894069738) to do the visualization.

**Comment by zzzucf** [comment]
Thank you, that solves my confusion. I really appreciate it.
