### ISSUE TITLE
May some errors when injecting...

### ISSUE THREAD

**Issue by RichardSunnyMeng** [YuxinWenRick/tree-ring-watermark#21]
I use the following settings to run the code with others unchanged.

> --w_channel 0
> --w_mask_shape circle
> --w_radius 32
> --w_pattern_const 1
> --w_pattern const/zero

But the accuracy is only 0% and 75% (where if a value is lower than 0 then it is assigned to 0, and if larger than 0 then it is assigned to 1). 
Under "const" pattern, the value of `reversed_latents_w_fft[0, 0, 32, 32]` is -250.2 but the target is 1. May I ask what is the reason for this?

Besides, I also add a pattern named "ring_bits" to assign a 0/1 bit to a ring randomly but acc is also 0.

**Comment by RichardSunnyMeng** [comment]
And I have a question. In optim_utils.py Line 213:

`init_latents_w = torch.fft.ifft2(torch.fft.ifftshift(init_latents_w_fft, dim=(-1, -2))).real`

Does the operation ".real" affect the already injected value?

**Comment by YuxinWenRick** [comment]
Hi @RichardSunnyMeng , I got TPR@1%FPR of 0.999 by running: `python run_tree_ring_watermark.py --run_name no_attack --w_channel 0 --w_pattern const --w_pattern_const 1 --start 0 --end 1000 --with_tracking`.

Or, do you mean the bit accuracy? I don't think tree-ring will give you a very high bit accuracy because the ddim inversion is not perfect. That's also the reason why `reversed_latents_w_fft[0, 0, 32, 32]` is not exact 1. Maybe you can try better inversion algorithms like this [paper](https://arxiv.org/abs/2311.18387)?

**Comment by RichardSunnyMeng** [comment]
> Hi @RichardSunnyMeng , I got TPR@1%FPR of 0.999 by running: `python run_tree_ring_watermark.py --run_name no_attack --w_channel 0 --w_pattern const --w_pattern_const 1 --start 0 --end 1000 --with_tracking`.
> 
> Or, do you mean the bit accuracy? I don't think tree-ring will give you a very high bit accuracy because the ddim inversion is not perfect. That's also the reason why `reversed_latents_w_fft[0, 0, 32, 32]` is not exact 1. Maybe you can try better inversion algorithms like this [paper](https://arxiv.org/abs/2311.18387)?

Oh, I got it, thank you!
