### ISSUE TITLE
why use negative no_w_metric and w_metric?

### ISSUE THREAD

**Issue by liwd190019** [YuxinWenRick/tree-ring-watermark#36]
https://github.com/YuxinWenRick/tree-ring-watermark/blob/3015283d9cf82e90b628f02ad2121bd37408ca9a/run_tree_ring_watermark.py#L141
https://github.com/YuxinWenRick/tree-ring-watermark/blob/3015283d9cf82e90b628f02ad2121bd37408ca9a/run_tree_ring_watermark.py#L142

Why do you use negative no_w_metric  and w_metric instead of the postive ones?

**Comment by YuxinWenRick** [comment]
Hi, @liwd190019, thanks for asking. It's a good question. For `preds` that we pass to `metrics.roc_curve` is the confidence score of being watermarked. If it's a watermarked image, this score should be larger. We negate it, since our metric is the distance, and we know that the distance is smaller for the watermarked images.

Let me know if you have further questions!
