### ISSUE TITLE
any method to speed up the image generating?

### ISSUE THREAD

**Issue by liwd190019** [YuxinWenRick/tree-ring-watermark#41]
Currently the model generates images on at a time, which is quite slow. Is there any method to speed up the image generation?

**Comment by YuxinWenRick** [comment]
Hi, sorry for the late response. I was busy with the ICLR deadline.

One thing I did was to split one job into 2 or more jobs. For example, instead of setting `start=0` and `end=1000` for one job, you can launch 2 jobs one with `start=0` and `end=500`, and one with `start=500` and `end=1000`. You have to save all the predictions, and combine them to calculate the ROC curve at the end.

Another you can do is to do batched generation. I think this can be easily done with small modification, since the diffusion pipeline supports batched inference. However, from my experience, this actually won't speed up the code too much, and sometimes on average, it's even slower than just using bs=1.
