### ISSUE TITLE
The chosen threshold α of p-value and the 1% of TPR@1%FPR

### ISSUE THREAD

**Issue by yfjn** [YuxinWenRick/tree-ring-watermark#43]
Hello, doctor, I appreciate your work. The following paragraph is from your paper:
```In addition to making detection results interpretable, P-values
can be used to set the threshold of detection, i.e., the watermark is “detected” when p is below a
chosen threshold α. By doing so, one can explicitly control the false positive rate α, making false
accusations statistically unlikely.
```
Could you please tell me the value of α you set in your experiment? Is it 1% as it comes from TPR@1%FPR? And I wonder why 1% is set in TPR@1%FPR and not some other number.

**Comment by YuxinWenRick** [comment]
Hey @rnqm, thanks for asking. If you want to use p-value as the metric (use this function: https://github.com/YuxinWenRick/tree-ring-watermark/blob/main/optim_utils.py#L231), you set the threshold to be 1%, since the 1% p-value means the probability of being a non-watermarked image is 1%.

However, for our experiments in the paper (we ran all the experiments before we wrote the p-value part), we use the empirical threshold and the distance to the original watermark pattern as the metric. In such a case, we find the empirical threshold by collecting a lot of metrics from non-watermarked images and setting the threshold to the bottom 1% quantile (here: https://github.com/YuxinWenRick/tree-ring-watermark/blob/main/run_tree_ring_watermark.py#L158-L161).

Please let me know if you have further questions.

**Comment by yfjn** [comment]
Thank you for your reply! Can I understand it as thresholds for these two metrics are both set to 1% and are both set empirically?
The TPR@1%FPR is evaluated based on a batch of images, but if I have a single image and want to determine whether it contains a watermark, can I only rely on the p-value?

**Comment by YuxinWenRick** [comment]
Yes, you are right. For empirical thresholds for our old metric, you need a batch of clean images to determine the threshold, but for p-value, you don't, since you just need to use 0.01.

**Comment by yfjn** [comment]
Thanks, doctor!
