### ISSUE TITLE
Code for computing p-value

### ISSUE THREAD

**Issue by zhanglijun95** [YuxinWenRick/tree-ring-watermark#9]
Hi author,

Thank you for your great work. I'm looking into your code, but I cannot find the one for computing p-value. Could you please provide that? Thank you!

Best,
Lijun

**Comment by YuxinWenRick** [comment]
Hi Lijun, sorry about the confusion, but you can find the function at: https://github.com/YuxinWenRick/tree-ring-watermark/blob/main/optim_utils.py#L231. It wasn't included in the experiment code because we conducted all the experiments before we added the p-value section. However, you can easily add or replace the function at this location: https://github.com/YuxinWenRick/tree-ring-watermark/blob/main/run_tree_ring_watermark.py#L127, similar to how you'd use `eval_watermark`.

Let me know if you have any further questions!

Best,
Yuxin
